# Generated by Django 3.1.2 on 2020-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='file',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='backgroundmusic',
            name='file',
            field=models.FileField(null=True, upload_to='musics'),
        ),
    ]
