-- --------------------------------------------------------
-- Host:                         www.ayuuu.cn
-- Server version:               10.5.6-MariaDB-1:10.5.6+maria~focal - mariadb.org binary distribution
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             11.1.0.6116
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table soul.scale_story: ~10 rows (approximately)
/*!40000 ALTER TABLE `scale_story` DISABLE KEYS */;
INSERT INTO `scale_story` (`id`, `level`, `title`, `markdown`, `url`, `type`, `html`) VALUES
	(3, 1, '你不完美，我也爱你', NULL, NULL, '漫画', '<div>\r\n    <img src="https://www.ayuuu.cn/static/html/images/你不完美_我也爱你_1.jpg" width="100%" />\r\n    <img src="https://www.ayuuu.cn/static/html/images/你不完美_我也爱你_2.jpg" width="100%" />\r\n    <img src="https://www.ayuuu.cn/static/html/images/你不完美_我也爱你_2.jpg" width="100%" />\r\n</div>'),
	(4, 1, '关于重复犯错，这是我听过最温柔的答案', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_12.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_13.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_14.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_15.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_16.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_17.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_18.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_19.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/关于重复犯错_这是我听过最温柔的答案_20.jpg" />\r\n</div>'),
	(5, 1, '和别人比较', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/和别人比较_12.jpg" />\r\n</div>'),
	(6, 1, '咨询师的解压方式', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/咨询师的解压方式_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/咨询师的解压方式_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/咨询师的解压方式_3.jpg" />\r\n</div>'),
	(7, 1, '垃圾口头禅回收站', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_12.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_13.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_14.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/垃圾口头禅回收站_15.jpg" />\r\n</div>'),
	(8, 1, '忘记撤回的那句话让我后悔了三年', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_12.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_13.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_14.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_15.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_16.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_17.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_18.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_19.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/忘记撤回的那句话让我后悔了三年_20.jpg" />\r\n</div>'),
	(9, 1, '真正爱你的人不会为你掏心掏肺', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_12.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_13.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_14.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_15.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/真正爱你的人不会为你掏心掏肺_16.jpg" />\r\n</div>'),
	(10, 1, '绝大多数关系，都是两个人一起搞砸的', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_12.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_13.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_14.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_15.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_16.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_17.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/绝大多数关系_都是两个人一起搞砸的_18.jpg" />\r\n</div>'),
	(11, 1, '老天爷为什么要这样对我', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/老天爷为什么要这样对我_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/老天爷为什么要这样对我_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/老天爷为什么要这样对我_2.jpg" />\r\n</div>'),
	(12, 1, '躺在舒适圈后，我越变越好了', NULL, NULL, '漫画', '<div>\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_1.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_2.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_3.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_4.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_5.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_6.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_7.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_8.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_9.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_10.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_11.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_12.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_13.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_14.jpg" />\r\n    <img width="100%" src="http://www.ayuuu.cn/static/html/images/躺在舒适圈后_我越变越好了_15.jpg" />\r\n</div>');
/*!40000 ALTER TABLE `scale_story` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
