INSERT INTO `soul`.`scale_evaluation`(`id`, `name`, `detail`, `warning`, `deleted`) VALUES (6, '明尼苏达（MMPI）抑郁量表', '\r\n这些题目供被试根据自己的实际情况对每个题目作出：“是”与“否”的回答。', '无', 0);


INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (24, '1.我的胃口很好。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (25, '2.我很容易被吵醒。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (26, '3.我的日常生活中，充满了使我感兴趣的事情。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (27, '4.我现在工作(学习)的能力，和从前差不多。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (28, '5.我很少有大便不通的毛病。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (29, '6.有时我真想骂人。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (30, '7.我发现我很难把注意力集中到一件工作上。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (31, '8.我很少担心自己的健康。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (32, '9.有时我真想摔东西。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (33, '10.我曾一连几天，几个星期，几个月什么也不想干，因为总是提不起精神。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (34, '11.我睡得不安，容易被惊醒。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (35, '12.我的判断力比以往任何时候都好。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (36, '13.我的身体和我大多数朋友一样地健康。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (37, '14.遇到同学或不常见朋友。除非他们先向我打招呼，不然我就装作没看见。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (38, '15.我和别人一见面就熟了(自来熟)', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (39, '16.一切事情都由老天爷安排好了。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (40, '17.我从未有过正常的生活。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (41, '18.我希望我能象别人那样快乐。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (42, '19.我有时捉弄动物。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (43, '20.我确实缺少自信心。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (44, '21.我总觉得人生是有价值的。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (45, '22.要使大数人相信事实的真相，是要经过一番辩论的。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (46, '23.我几乎每星期都去教堂(或常去寺庙)。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (47, '24.我相信善有善报，恶有恶报。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (48, '25.我似乎对什么事情都不在乎。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (49, '26.我经常是快乐的。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (50, '27.我似乎和我周围的人一样精明能干。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (51, '28.我从来没有吐过血，或咯过血。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (52, '29.我不为得病而担心。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (53, '30.批评和责骂都使我非常伤心。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (54, '31.有时我觉得我真是毫无用处。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (55, '32.有时我想借故和别人打架。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (56, '33.大多数晚上我睡觉时，不受什么思想干扰', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (57, '34.近几年来大部分时间，我的身体都很好', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (58, '35.我从来没有过抽疯的毛病', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (59, '36.现在我的体重既没有增加也没有减轻。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (60, '37.我容易哭。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (61, '38.我不能象从前那样理解我所读的东西了。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (62, '39.在我一生中，我从来没有感觉到象现在这么好。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (63, '40.我的记忆力似乎不错。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (64, '41.我怕自己会发疯。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (65, '42.许多时候，我觉得浑身无力。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (66, '43.有时，当我难为情的时候，会出很多汗，这使我非常苦恼。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (67, '44.我没哮喘这一类病。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (68, '45.我喜欢许多不同种类的游戏和娱乐。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (69, '46.我喜欢和异性说笑。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (70, '47.我有时阻止别人做某些事，并不是因为那种事有多大影响，而是在道义上我应该干预他。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (71, '48.我有很多心事。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (72, '49.我常梦到一些不可告人的事。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (73, '50.我相信我并不比别人更为神经过敏。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (74, '51.我有时无缘无故地，甚至在不顺利的时候也会觉得非常快乐。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (75, '52.做什么事情，我都感到难以开头。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (76, '53.即使在冷天我也很容易出汗。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (77, '54.我离家外出的时候，从来不担心家里门窗是否关好锁好了。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (78, '55.我不责怪一个欺负了处找没趣的人。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (79, '56.我有时精力充沛。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (80, '57.偶尔我听了下流的笑话也会发笑。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (81, '58.恶心呕吐的毛病使我苦恼。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (82, '59.我总是在很紧张的情况下工作的。', 0, 6);
INSERT INTO `soul`.`scale_question`(`id`, `content`, `deleted`, `evaluation_id`) VALUES (83, '60.有些时候，我会无缘无故地觉得非常愉快', 0, 6);


INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (91, '是', 0, 0, 24);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (92, '否', 1, 0, 24);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (93, '是', 1, 0, 25);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (94, '否', 0, 0, 25);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (95, '是', 0, 0, 26);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (96, '否', 1, 0, 26);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (97, '是', 0, 0, 27);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (98, '否', 1, 0, 27);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (99, '是', 0, 0, 28);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (100, '否', 1, 0, 28);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (101, '是', 0, 0, 29);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (102, '否', 1, 0, 29);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (103, '是', 1, 0, 30);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (104, '否', 0, 0, 30);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (105, '是', 0, 0, 31);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (106, '否', 1, 0, 31);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (107, '是', 0, 0, 32);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (108, '否', 1, 0, 32);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (109, '是', 1, 0, 33);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (110, '否', 0, 0, 33);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (111, '是', 1, 0, 34);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (112, '否', 0, 0, 34);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (113, '是', 0, 0, 35);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (114, '否', 1, 0, 35);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (115, '是', 0, 0, 36);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (116, '否', 1, 0, 36);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (117, '是', 1, 0, 37);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (118, '否', 0, 0, 37);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (119, '是', 0, 0, 38);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (120, '否', 1, 0, 38);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (121, '是', 0, 0, 39);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (122, '否', 1, 0, 39);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (123, '是', 0, 0, 40);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (124, '否', 1, 0, 40);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (125, '是', 1, 0, 41);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (126, '否', 0, 0, 41);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (127, '是', 0, 0, 42);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (128, '否', 1, 0, 42);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (129, '是', 1, 0, 43);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (130, '否', 0, 0, 43);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (131, '是', 0, 0, 44);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (132, '否', 1, 0, 44);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (133, '是', 0, 0, 45);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (134, '否', 1, 0, 45);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (135, '是', 0, 0, 46);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (136, '否', 1, 0, 46);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (137, '是', 0, 0, 47);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (138, '否', 1, 0, 47);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (139, '是', 1, 0, 48);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (140, '否', 0, 0, 48);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (141, '是', 0, 0, 49);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (142, '否', 1, 0, 49);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (143, '是', 0, 0, 50);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (144, '否', 1, 0, 50);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (145, '是', 1, 0, 51);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (146, '否', 0, 0, 51);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (147, '是', 0, 0, 52);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (148, '否', 1, 0, 52);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (149, '是', 1, 0, 53);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (150, '否', 0, 0, 53);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (151, '是', 1, 0, 54);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (152, '否', 0, 0, 54);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (153, '是', 0, 0, 55);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (154, '否', 1, 0, 55);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (155, '是', 0, 0, 56);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (156, '否', 1, 0, 56);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (157, '是', 0, 0, 57);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (158, '否', 1, 0, 57);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (159, '是', 0, 0, 58);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (160, '否', 1, 0, 58);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (161, '是', 0, 0, 59);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (162, '否', 1, 0, 59);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (163, '是', 1, 0, 60);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (164, '否', 0, 0, 60);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (165, '是', 1, 0, 61);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (166, '否', 0, 0, 61);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (167, '是', 0, 0, 62);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (168, '否', 1, 0, 62);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (169, '是', 0, 0, 63);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (170, '否', 1, 0, 63);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (171, '是', 1, 0, 64);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (172, '否', 0, 0, 64);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (173, '是', 1, 0, 65);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (174, '否', 0, 0, 65);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (175, '是', 0, 0, 66);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (176, '否', 1, 0, 66);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (177, '是', 1, 0, 67);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (178, '否', 0, 0, 67);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (179, '是', 0, 0, 68);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (180, '否', 1, 0, 68);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (181, '是', 0, 0, 69);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (182, '否', 1, 0, 69);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (183, '是', 0, 0, 70);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (184, '否', 1, 0, 70);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (185, '是', 1, 0, 71);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (186, '否', 0, 0, 71);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (187, '是', 0, 0, 72);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (188, '否', 1, 0, 72);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (189, '是', 0, 0, 73);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (190, '否', 1, 0, 73);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (191, '是', 0, 0, 74);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (192, '否', 1, 0, 74);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (193, '是', 1, 0, 75);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (194, '否', 0, 0, 75);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (195, '是', 0, 0, 76);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (196, '否', 1, 0, 76);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (197, '是', 0, 0, 77);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (198, '否', 1, 0, 77);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (199, '是', 0, 0, 78);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (200, '否', 1, 0, 78);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (201, '是', 0, 0, 79);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (202, '否', 1, 0, 79);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (203, '是', 0, 0, 80);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (204, '否', 1, 0, 80);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (205, '是', 1, 0, 81);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (206, '否', 0, 0, 81);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (207, '是', 1, 0, 82);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (208, '否', 0, 0, 82);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (209, '是', 0, 0, 83);
INSERT INTO `soul`.`scale_option`(`id`, `content`, `score`, `deleted`, `question_id`) VALUES (210, '否', 1, 0, 83);


