# Generated by Django 3.1.2 on 2020-10-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('title', models.TextField(null=True)),
                ('markdown', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluationrate',
            name='warning',
        ),
        migrations.AddField(
            model_name='evaluationrate',
            name='advice',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluationrate',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
